"""articles table added

Revision ID: c7d3b4cedb0d
Revises: 8010b8c6ae50
Create Date: 2025-03-17 00:00:21.606561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7d3b4cedb0d'
down_revision: Union[str, None] = '8010b8c6ae50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cover_image', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['content.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('book')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cover_image', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], name='book_content_id_fkey'),
    sa.ForeignKeyConstraint(['id'], ['content.id'], name='book_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='book_pkey')
    )
    op.drop_table('books')
    # ### end Alembic commands ###
